image: 
replicas: 1
initImage: 
servicePort: 80
serviceTargetPort: 8080
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 2048Mi
livenessProbe:
  initialDelaySeconds: 1800
  timeoutSeconds: 3
  httpGet:
    path: /counter
    port: 8080
reportService:
  user: sysadmin@mail.com
  pass: P@ssw0rd

redis:
  cluster:
    enabled: false
  usePassword: true
  password: P@ssw0rd
  redisPort: 6379
  master:
    persistence: false