apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
#    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Release.Name }}.demo.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-counter
          servicePort: 80