apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-name
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  NAME: DamaoShao